n1 = int(input("type the number you know to want the multiplication table: "))
print("the table of ", n1)
print("="*10)

print(n1 * 1)
print(n1 * 2)
print(n1 * 3)
print(n1 * 4)
print(n1 * 5)
print(n1 * 6)
print(n1 * 7)
print(n1 * 8)
print(n1 * 9)
print(n1 * 10)