n1 = input("type something: ")

print("the type of this value is?", type(n1))
print("Does it have spaces?", n1.isspace())
print("is it a number? ", n1.isnumeric())
print("is it an alphabetical?", n1.isalpha())
print("is it an alphanumeric?", n1.isalnum())
print("is it an upper case? ", n1.isupper())
print("is it a lower case?", n1.islower())
print("is it a title-case? ", n1.istitle())
